# Generated by Django 4.2 on 2023-05-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgroundd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
