# Generated by Django 4.2 on 2023-05-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgroundd', '0002_alter_scheduler_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='appointment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
