# Generated by Django 4.2 on 2023-05-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgroundd', '0005_veterinaryscheduler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VeterinaryScheduler',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='appointment',
        ),
    ]
