# Generated by Django 4.2 on 2023-05-29 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgroundd', '0006_delete_veterinaryscheduler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='appointment',
            field=models.CharField(default=datetime.datetime(2023, 5, 29, 7, 19, 50, 289185, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
