# Generated by Django 4.2 on 2023-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgroundd', '0007_scheduler_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='appointment',
        ),
    ]
