# Generated by Django 4.2 on 2023-05-29 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgroundd', '0008_remove_scheduler_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='appointment',
            field=models.CharField(default=datetime.datetime(2023, 5, 29, 7, 27, 22, 936712, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
